name: restaurante_app
description: "Comida rápida, asados al carbón y micheladas bien frías con estilo ochentero. Sabor callejero, ambiente retro."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  sqflite: ^2.4.1
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.3
  image_picker: ^1.1.2
  charts_flutter: ^0.12.0
  pdf: ^3.11.3
  firebase_storage: ^12.4.3
  fl_chart: ^1.0.0
  http: ^1.3.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  path_provider: ^2.0.11
  share_plus: ^11.0.0
  printing: ^5.14.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_2.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700